title: Nybles
description: Tech Newsletter of IIIT Allahabad
# author: Nybles

logo: /nybles.github.io/static/logo/Logo_2_transparent.png
github: https://github.com/nybles
# about: IIIT Allahabad

baseurl: ""
url: "https://nybles.github.io/"

theme_color: "#d84315"
theme_highlight_color: "#e95420"
theme_header_color: "#ffffff"

comments: true

disqus_shortname: geekhaven-blog
google_analytics: UA-82762642-3

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 10
per_page: 10
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
